version: '3.7'
services:

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/code/redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.10-alpine
    restart: "always"
    command: postgres
    volumes:
      - ./postgres:/code/postgres
    environment:
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_DATABASE=postgres
    ports:
      - "5431:5432"


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: celery -A support worker -l info
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

volumes:
  postgres:
  redis: